import { testAdRewardService } from './AdRewardService.test.js';
import { testAudioService } from './AudioService.test.js';
import { testCombatResolver } from './CombatResolver.test.js';
import { testLootGenerator } from './LootGenerator.test.js';
import { testLayerBoundary } from './LayerBoundary.test.js';
import { testP0CocosUiBindingFactory } from './P0CocosUiBindingFactory.test.js';
import { testP0CocosUiPresenter } from './P0CocosUiPresenter.test.js';
import { testP0CocosUiRuntime } from './P0CocosUiRuntime.test.js';
import { testP0UiNodeBindingCoverage } from './P0UiNodeBindingCoverage.test.js';
import { testP0UiNodeBindingSchema } from './P0UiNodeBinding.schema.test.js';
import { testP0UiRequestRouter } from './P0UiRequestRouter.test.js';
import { testP0UiRequests } from './P0UiRequests.test.js';
import { testP0UiViewModel } from './P0UiViewModel.test.js';
import { testRewardService } from './RewardService.test.js';
import { testSaveVersionMigrator } from './SaveVersionMigrator.test.js';
import { testTrainModuleSystem } from './TrainModuleSystem.test.js';
import { testUiConfigSchema } from './UiConfig.schema.test.js';
import { testPrototypeLoop } from '../integration/prototypeLoop.test.js';

await testLootGenerator();
await testAudioService();
await testCombatResolver();
await testRewardService();
await testSaveVersionMigrator();
await testAdRewardService();
await testTrainModuleSystem();
await testUiConfigSchema();
await testP0UiNodeBindingSchema();
await testP0UiRequests();
await testP0UiViewModel();
await testP0CocosUiPresenter();
await testP0CocosUiRuntime();
await testP0UiNodeBindingCoverage();
await testP0CocosUiBindingFactory();
await testP0UiRequestRouter();
await testLayerBoundary();
await testPrototypeLoop();
